name: 'Coverage Report'
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  coverage_report:
    name: "Codecov Report"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
    run: yarn test:coverage

